# Generated by Django 5.2 on 2025-04-22 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEventSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vat', 'מע״מ'), ('tax', 'מקדמות מס'), ('salary', 'שכר'), ('bituach', 'ביטוח לאומי'), ('bituach_nikuy', 'ביטוח לאומי ניכויים'), ('tax_nikuy', 'מס הכנסה ניכויים'), ('doch_shnati', 'דוח שנתי'), ('hatzharat_hon', 'הצהרת הון'), ('other', 'אחר')], max_length=20)),
                ('frequency', models.CharField(choices=[('monthly', 'חודשי'), ('bimonthly', 'דו-חודשי'), ('quarterly', 'רבעוני'), ('once', 'חד פעמי')], default='monthly', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_settings', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Referent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.referent'),
        ),
        migrations.CreateModel(
            name='FollowUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vat', 'מע״מ'), ('tax', 'מקדמות מס'), ('salary', 'שכר'), ('bituach', 'ביטוח לאומי'), ('bituach_nikuy', 'ביטוח לאומי ניכויים'), ('tax_nikuy', 'מס הכנסה ניכויים'), ('doch_shnati', 'דוח שנתי'), ('hatzharat_hon', 'הצהרת הון'), ('other', 'אחר')], max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('bookkeeping_received', models.BooleanField(default=False)),
                ('bookkeeping_note', models.TextField(blank=True)),
                ('bookkeeping_entered', models.BooleanField(default=False)),
                ('approval_to_report', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('payment_note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.client')),
            ],
            options={
                'unique_together': {('client', 'event_type', 'month', 'year')},
            },
        ),
    ]
