# Generated by Django 5.2 on 2025-04-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupevent',
            old_name='bookkeeping_note',
            new_name='materials_note',
        ),
        migrations.RenameField(
            model_name='followupevent',
            old_name='bookkeeping_entered',
            new_name='materials_processed',
        ),
        migrations.RenameField(
            model_name='followupevent',
            old_name='bookkeeping_received',
            new_name='materials_received',
        ),
    ]
